In [261]:
#import libraries
import pandas as pd
import seaborn as sns

In [263]:
df = pd.read_csv(r'fifa_players.csv')

In [265]:
df.head(2)

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
0,L. Messi,Lionel Andrés Messi Cuccittini,6/24/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,94,48,22,94,94,75,96,33,28,26
1,C. Eriksen,Christian Dannemann Eriksen,2/14/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,89,46,56,84,91,67,88,59,57,22

In [267]:
df.shape

(17954, 51)

In [269]:
#it contains more than 17954 rows we have to clean that so lets do that

In [271]:
df2 = df.drop(['body_type','penalties','short_passing','curve','long_passing','freekick_accuracy','heading_accuracy','crossing','national_jersey_number','long_shots','reactions','sprint_speed','national_team_position','national_rating','release_clause_euro','international_reputation(1-5)','weak_foot(1-5)','age','full_name','balance','agility', 'height_cm', 'weight_kgs', 'composure','jumping','standing_tackle','aggression','positioning','marking','vision','wage_euro','potential','value_euro'], axis=1, errors='ignore')

In [273]:
df2.head(2)

,name,birth_date,positions,nationality,overall_rating,preferred_foot,skill_moves(1-5),national_team,finishing,volleys,dribbling,ball_control,acceleration,shot_power,stamina,strength,interceptions,sliding_tackle
0,L. Messi,6/24/1987,"CF,RW,ST",Argentina,94,Left,4,Argentina,95,86,97,96,91,85,72,66,22,26
1,C. Eriksen,2/14/1992,"CAM,RM,CM",Denmark,88,Right,4,Denmark,81,80,84,91,76,84,92,58,56,22

In [275]:
df2['birth_date'] = pd.to_datetime(df2['birth_date'])

In [277]:
df2['year'] = df2['birth_date'].apply(lambda x: x.strftime('%Y'))

In [279]:
df2 = df2.drop(['birth_date','volleys','shot_power'], axis=1, errors='ignore')

In [281]:
df2.head(2)

,name,positions,nationality,overall_rating,preferred_foot,skill_moves(1-5),national_team,finishing,dribbling,ball_control,acceleration,stamina,strength,interceptions,sliding_tackle,year
0,L. Messi,"CF,RW,ST",Argentina,94,Left,4,Argentina,95,97,96,91,72,66,22,26,1987
1,C. Eriksen,"CAM,RM,CM",Denmark,88,Right,4,Denmark,81,84,91,76,92,58,56,22,1992

In [283]:
#age of the Player

In [285]:
df2['year']=df2['year'].astype(int)

In [287]:
df2['year']  = 2024-df2['year']

In [289]:
df2.head(2)

,name,positions,nationality,overall_rating,preferred_foot,skill_moves(1-5),national_team,finishing,dribbling,ball_control,acceleration,stamina,strength,interceptions,sliding_tackle,year
0,L. Messi,"CF,RW,ST",Argentina,94,Left,4,Argentina,95,97,96,91,72,66,22,26,37
1,C. Eriksen,"CAM,RM,CM",Denmark,88,Right,4,Denmark,81,84,91,76,92,58,56,22,32

In [291]:
df2=df2[df2['year']<40]

In [293]:
df2.shape

(16979, 16)

In [295]:
#cleanup null values

In [297]:
df2.isna().sum()

name                    0
positions               0
nationality             0
overall_rating          0
preferred_foot          0
skill_moves(1-5)        0
national_team       16147
finishing               0
dribbling               0
ball_control            0
acceleration            0
stamina                 0
strength                0
interceptions           0
sliding_tackle          0
year                    0
dtype: int64

In [299]:
df2[df2['national_team'].isna()==1]

,name,positions,nationality,overall_rating,preferred_foot,skill_moves(1-5),national_team,finishing,dribbling,ball_control,acceleration,stamina,strength,interceptions,sliding_tackle,year
4,K. Koulibaly,CB,Senegal,88,Right,2,NaN,22,69,63,70,75,94,88,87,33
16,M. Škriniar,CB,Slovakia,86,Right,2,NaN,42,59,67,70,77,85,86,84,29
17,Fernandinho,CDM,Brazil,87,Right,3,NaN,69,77,82,68,84,76,89,80,39
18,G. Higuaín,ST,Argentina,87,Right,3,NaN,91,83,84,70,70,85,20,18,37
19,I. Rakitić,"CM,CDM",Croatia,87,Right,3,NaN,79,82,85,66,83,71,81,73,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,R. McKenzie,"RM,CAM,CM",Scotland,67,Right,3,NaN,61,64,66,83,75,64,41,18,31
17950,M. Sipľak,LB,Slovakia,59,Left,2,NaN,19,52,53,70,66,70,55,60,28
17951,J. Bekkema,GK,Netherlands,59,Right,1,NaN,9,12,18,27,25,63,10,13,28
17952,A. Al Yami,"ST,LM",Saudi Arabia,59,Right,3,NaN,60,57,56,84,58,49,15,17,27
17953,Júnior Brumado,ST,Brazil,59,Right,2,NaN,58,58,56,67,57,67,20,21,25

In [301]:
#removed players who are not in the national_team

In [303]:
df2=df2.dropna()

In [305]:
df2.shape

(832, 16)

In [307]:
#we dont want gk in this letms remove it

In [309]:
df2 = df2[df2['positions'] != 'GK']

In [313]:
df2.head(2)

,name,positions,nationality,overall_rating,preferred_foot,skill_moves(1-5),national_team,finishing,dribbling,ball_control,acceleration,stamina,strength,interceptions,sliding_tackle,year
0,L. Messi,"CF,RW,ST",Argentina,94,Left,4,Argentina,95,97,96,91,72,66,22,26,37
1,C. Eriksen,"CAM,RM,CM",Denmark,88,Right,4,Denmark,81,84,91,76,92,58,56,22,32

In [315]:
df2.shape

(737, 16)

In [317]:
#we want only best players rating over 80

In [327]:
df2=df2[df2['overall_rating']>80]

In [349]:
df2 = df2.drop(['nationality','skill_moves(1-5)','sliding_tackle'], axis=1, errors='ignore')

In [351]:
df2.shape

(45, 13)

In [353]:
df2.head()

,name,positions,overall_rating,preferred_foot,national_team,finishing,dribbling,ball_control,acceleration,stamina,strength,interceptions,year
0,L. Messi,"CF,RW,ST",94,Left,Argentina,95,97,96,91,72,66,22,37
1,C. Eriksen,"CAM,RM,CM",88,Right,Denmark,81,84,91,76,92,58,56,32
2,P. Pogba,"CM,CAM",88,Right,France,75,87,90,71,88,87,64,31
3,L. Insigne,"LW,ST",88,Right,Italy,77,90,93,94,75,44,26,33
5,V. van Dijk,CB,88,Right,Netherlands,52,70,76,74,75,92,88,33

In [355]:
df2=df2.rename(columns={'name':'Name',
                        'positions':'Played Positions',
                        'overall_rating':'Rating',
                        'preferred_foot':'Strong Foot',
                        'national_team':'National Team',
                        'finishing':'Finishing',
                        'dribbling':'Dribbling',
                        'ball_control':'Ball Control',
                        'acceleration':'Acceleration',
                        'stamina':'Stamina',
                        'strength':'Strength',
                        'interceptions':'Interceptions',
                        'year':'Age'
                        })

In [357]:
df2.head(2)

,Name,Played Positions,Rating,Strong Foot,National Team,Finishing,Dribbling,Ball Control,Acceleration,Stamina,Strength,Interceptions,Age
0,L. Messi,"CF,RW,ST",94,Left,Argentina,95,97,96,91,72,66,22,37
1,C. Eriksen,"CAM,RM,CM",88,Right,Denmark,81,84,91,76,92,58,56,32

In [359]:
#reorder columns

In [367]:
df2=df2[['Name','Age','Rating','Played Positions','National Team','Strong Foot','Finishing','Dribbling','Ball Control','Acceleration','Stamina','Strength','Interceptions']]

In [369]:
df2.head(2)

,Name,Age,Rating,Played Positions,National Team,Strong Foot,Finishing,Dribbling,Ball Control,Acceleration,Stamina,Strength,Interceptions
0,L. Messi,37,94,"CF,RW,ST",Argentina,Left,95,97,96,91,72,66,22
1,C. Eriksen,32,88,"CAM,RM,CM",Denmark,Right,81,84,91,76,92,58,56

In [379]:
df2= df2.sort_values(by='Rating', ascending=False)

In [381]:
df2

,Name,Age,Rating,Played Positions,National Team,Strong Foot,Finishing,Dribbling,Ball Control,Acceleration,Stamina,Strength,Interceptions
0,L. Messi,37,94,"CF,RW,ST",Argentina,Left,95,97,96,91,72,66,22
17944,Cristiano Ronaldo,39,94,"ST,LW",Portugal,Right,94,88,94,89,88,79,29
17943,Neymar Jr,32,92,"LW,CAM",Brazil,Right,87,96,95,94,81,49,36
17941,K. De Bruyne,33,91,"CAM,CM",Belgium,Right,82,86,91,78,89,75,61
17940,E. Hazard,33,91,"LW,CF",Belgium,Right,84,95,94,94,83,66,41
17938,L. Suárez,37,91,ST,Uruguay,Right,92,86,88,83,90,83,41
17934,T. Kroos,34,90,CM,Germany,Right,76,81,90,64,75,73,76
17933,D. Godín,38,90,CB,Uruguay,Right,42,53,76,64,66,88,88
17937,H. Kane,31,90,ST,England,Right,94,80,84,68,89,84,35
17935,R. Lewandowski,36,90,ST,Poland,Right,91,85,89,77,78,84,39
17931,Sergio Ramos,38,90,CB,Spain,Right,63,65,83,76,84,83,88
15,P. Dybala,31,89,"CAM,RW",Argentina,Left,84,92,92,87,80,65,32
14,M. Salah,32,89,"RW,ST",Egypt,Left,90,89,88,94,84,70,55
13,A. Griezmann,33,89,"CF,ST",France,Left,89,87,90,88,86,62,49
10,Sergio Busquets,36,89,"CDM,CM",Spain,Right,67,80,88,50,86,77,87
9,E. Cavani,37,89,ST,Uruguay,Right,89,80,82,75,92,78,48
7,S. Agüero,36,89,ST,Argentina,Right,93,89,89,88,76,73,24
17929,N. Kanté,33,89,"CDM,CM",France,Right,65,79,80,82,97,76,92
3,L. Insigne,33,88,"LW,ST",Italy,Right,77,90,93,94,75,44,26
17924,G. Bale,35,88,"RW,LW,ST",Wales,Left,86,87,85,94,75,80,59
17926,M. Reus,35,88,"CAM,LM,ST",Germany,Right,87,87,87,86,76,67,48
17925,M. Hummels,36,88,CB,Germany,Right,55,68,81,53,66,84,92
2,P. Pogba,31,88,"CM,CAM",France,Right,75,87,90,71,88,87,64
1,C. Eriksen,32,88,"CAM,RM,CM",Denmark,Right,81,84,91,76,92,58,56
6,K. Mbappé,26,88,"RW,ST,RM",France,Right,88,90,91,96,83,71,38
5,V. van Dijk,33,88,CB,Netherlands,Right,52,70,76,74,75,92,88
31,M. Icardi,31,87,ST,Argentina,Right,91,77,81,77,69,76,22
28,Isco,32,87,"CAM,CM,LW",Spain,Right,79,94,95,75,70,59,64
26,C. Immobile,34,87,ST,Italy,Right,90,83,83,78,80,76,40
25,Thiago,33,87,"CM,CAM,CDM",Spain,Right,69,90,90,78,75,59,78
24,Jordi Alba,35,87,LB,Spain,Left,73,80,84,93,91,61,84
23,T. Alderweireld,35,87,CB,Belgium,Right,45,62,75,61,76,79,87
17916,R. Sterling,30,87,"RW,LW",England,Right,79,88,87,95,78,52,30
21,D. Mertens,37,87,"CF,ST",Belgium,Right,86,91,89,93,75,42,36
20,J. Vertonghen,37,87,CB,Belgium,Left,56,71,77,61,75,79,89
29,J. Rodríguez,33,87,"CAM,CM,RM",Colombia,Left,83,85,90,73,70,68,55
17905,T. Müller,35,86,"CAM,RM,RW,CF",Germany,Right,87,75,82,73,87,68,58
17915,L. Sané,28,86,LW,Germany,Left,81,88,85,93,79,70,34
17914,Bernardo Silva,30,86,"CAM,CM,RW,RM",Portugal,Left,75,92,91,86,86,50,49
17913,J. Kimmich,29,86,"RB,CM,CDM",Germany,Right,66,80,85,78,94,64,80
17909,R. Varane,31,86,CB,France,Right,40,57,77,83,73,84,82
17908,M. Verratti,32,86,"CM,CDM",Italy,Right,60,90,88,69,77,52,84
17907,R. Lukaku,31,86,ST,Belgium,Left,86,78,71,75,81,94,27
17902,L. Bonucci,37,86,CB,Italy,Right,48,69,75,57,71,83,90
17903,Azpilicueta,35,86,"RB,CB",Spain,Right,46,69,77,76,87,71,89

In [383]:
#reset index

In [385]:
df2.reset_index(drop=True)

,Name,Age,Rating,Played Positions,National Team,Strong Foot,Finishing,Dribbling,Ball Control,Acceleration,Stamina,Strength,Interceptions
0,L. Messi,37,94,"CF,RW,ST",Argentina,Left,95,97,96,91,72,66,22
1,Cristiano Ronaldo,39,94,"ST,LW",Portugal,Right,94,88,94,89,88,79,29
2,Neymar Jr,32,92,"LW,CAM",Brazil,Right,87,96,95,94,81,49,36
3,K. De Bruyne,33,91,"CAM,CM",Belgium,Right,82,86,91,78,89,75,61
4,E. Hazard,33,91,"LW,CF",Belgium,Right,84,95,94,94,83,66,41
5,L. Suárez,37,91,ST,Uruguay,Right,92,86,88,83,90,83,41
6,T. Kroos,34,90,CM,Germany,Right,76,81,90,64,75,73,76
7,D. Godín,38,90,CB,Uruguay,Right,42,53,76,64,66,88,88
8,H. Kane,31,90,ST,England,Right,94,80,84,68,89,84,35
9,R. Lewandowski,36,90,ST,Poland,Right,91,85,89,77,78,84,39
10,Sergio Ramos,38,90,CB,Spain,Right,63,65,83,76,84,83,88
11,P. Dybala,31,89,"CAM,RW",Argentina,Left,84,92,92,87,80,65,32
12,M. Salah,32,89,"RW,ST",Egypt,Left,90,89,88,94,84,70,55
13,A. Griezmann,33,89,"CF,ST",France,Left,89,87,90,88,86,62,49
14,Sergio Busquets,36,89,"CDM,CM",Spain,Right,67,80,88,50,86,77,87
15,E. Cavani,37,89,ST,Uruguay,Right,89,80,82,75,92,78,48
16,S. Agüero,36,89,ST,Argentina,Right,93,89,89,88,76,73,24
17,N. Kanté,33,89,"CDM,CM",France,Right,65,79,80,82,97,76,92
18,L. Insigne,33,88,"LW,ST",Italy,Right,77,90,93,94,75,44,26
19,G. Bale,35,88,"RW,LW,ST",Wales,Left,86,87,85,94,75,80,59
20,M. Reus,35,88,"CAM,LM,ST",Germany,Right,87,87,87,86,76,67,48
21,M. Hummels,36,88,CB,Germany,Right,55,68,81,53,66,84,92
22,P. Pogba,31,88,"CM,CAM",France,Right,75,87,90,71,88,87,64
23,C. Eriksen,32,88,"CAM,RM,CM",Denmark,Right,81,84,91,76,92,58,56
24,K. Mbappé,26,88,"RW,ST,RM",France,Right,88,90,91,96,83,71,38
25,V. van Dijk,33,88,CB,Netherlands,Right,52,70,76,74,75,92,88
26,M. Icardi,31,87,ST,Argentina,Right,91,77,81,77,69,76,22
27,Isco,32,87,"CAM,CM,LW",Spain,Right,79,94,95,75,70,59,64
28,C. Immobile,34,87,ST,Italy,Right,90,83,83,78,80,76,40
29,Thiago,33,87,"CM,CAM,CDM",Spain,Right,69,90,90,78,75,59,78
30,Jordi Alba,35,87,LB,Spain,Left,73,80,84,93,91,61,84
31,T. Alderweireld,35,87,CB,Belgium,Right,45,62,75,61,76,79,87
32,R. Sterling,30,87,"RW,LW",England,Right,79,88,87,95,78,52,30
33,D. Mertens,37,87,"CF,ST",Belgium,Right,86,91,89,93,75,42,36
34,J. Vertonghen,37,87,CB,Belgium,Left,56,71,77,61,75,79,89
35,J. Rodríguez,33,87,"CAM,CM,RM",Colombia,Left,83,85,90,73,70,68,55
36,T. Müller,35,86,"CAM,RM,RW,CF",Germany,Right,87,75,82,73,87,68,58
37,L. Sané,28,86,LW,Germany,Left,81,88,85,93,79,70,34
38,Bernardo Silva,30,86,"CAM,CM,RW,RM",Portugal,Left,75,92,91,86,86,50,49
39,J. Kimmich,29,86,"RB,CM,CDM",Germany,Right,66,80,85,78,94,64,80
40,R. Varane,31,86,CB,France,Right,40,57,77,83,73,84,82
41,M. Verratti,32,86,"CM,CDM",Italy,Right,60,90,88,69,77,52,84
42,R. Lukaku,31,86,ST,Belgium,Left,86,78,71,75,81,94,27
43,L. Bonucci,37,86,CB,Italy,Right,48,69,75,57,71,83,90
44,Azpilicueta,35,86,"RB,CB",Spain,Right,46,69,77,76,87,71,89

In [389]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ------ -------------------------------- 41.0/250.9 kB 487.6 kB/s eta 0:00:01
   ------------------ ------------------- 122.9/250.9 kB 901.1 kB/s eta 0:00:01
   ----------------------------------- ---- 225.3/250.9 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.3 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [393]:
# Save the DataFrame to an Excel file
df2.to_excel('Football.xlsx', index=False)